### PR TITLE
Use new URL for searches. Index starts at 0 now

### PR DESCRIPTION
**Pull request by fernandog**
@gfjardim uses the same URL from LTV. 

~~I didn't test. But in my app that URL works~~
Tested ok

Logs:

```
15:55:13.558 T:1363145712   DEBUG: ### [Legendas.TV] - Message: Retrieving results to id[xxxxx]
15:55:13.574 T:1336304624   DEBUG: ### [Legendas.TV] - Message: Retrieving page [0] for Movie[Prison Break], Id[xxxxx].
15:55:13.574 T:1336304624   DEBUG: ### [Legendas.TV] - Opening URL: (http://legendas.tv/legenda/busca/-/-/-/0/xxxxx)
15:55:13.575 T:1344693232   DEBUG: ### [Legendas.TV] - Message: Retrieving page [1] for Movie[Prison Break], Id[xxxxx].
15:55:13.575 T:1344693232   DEBUG: ### [Legendas.TV] - Opening URL: (http://legendas.tv/legenda/busca/-/-/-/1/xxxxx)
15:55:13.602 T:1326445552   DEBUG: ### [Legendas.TV] - Message: Retrieving page [2] for Movie[Prison Break], Id[xxxxx].
15:55:13.603 T:1326445552   DEBUG: ### [Legendas.TV] - Opening URL: (http://legendas.tv/legenda/busca/-/-/-/2/xxxxx)
15:55:14.612 T:1344693232   DEBUG: ### [Legendas.TV] - Error: Failed retrieving page [1] for Movie[Prison Break], Id[xxxxx].
15:55:14.616 T:1326445552   DEBUG: ### [Legendas.TV] - Error: Failed retrieving page [2] for Movie[Prison Break], Id[xxxxx].
15:55:14.818 T:1336304624   DEBUG: ### [Legendas.TV] - Message: Retrieved [16] results for page [0], Movie[], Id[xxxxx].
```

### CODE REVIEW

**Comment by fernandog** [comment]
@gfjardim can you check your `.kodi/temp` folder and see if you have tons of `rarfolder` folders?

**Comment by fernandog** [comment]
@gfjardim is this repo the official one ?

**Comment by MediaBrasil** [comment]
@fernandog, sim é o git do mantenedor.

@gfjardim, em meus testes o addon esta com problemas no Kodi 18, baixa as legendas mas não está extraindo, o opensubtitles se encontra ok, quando puder verificar, eu agradeço.

**Comment by gfjardim** [comment]
Pessoal, vou demorar uns dias pra poder verificar e aceitar o PR. Desculpe
a demora e o incômodo.

Em 24 de jul de 2017 23:02, "MediaBrasil" <notifications@github.com>
escreveu:

@fernandog <https://github.com/fernandog>, sim é o git do mantenedor.

@gfjardim <https://github.com/gfjardim>, em meus testes o addon esta com
problemas no Kodi 18, baixa as legendas mas não está extraindo, o
opensubtitles se encontra ok, quando puder verificar, eu agradeço.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gfjardim/service.subtitles.legendastv/pull/19#issuecomment-317606753>,
or mute the thread

**Comment by fernandog** [comment]
@MediaBrasil mine works ok. Sometimes it crashes because of encoding issues:

It crashes because of "Legenda Forçada" but the other one was extracted ok

 ```
09:53:26.823 T:1472197616   DEBUG: ### [Legendas.TV] - Opening URL: (http://legendas.tv/downloadarquivo/5957f03adb0b5)
09:53:30.060 T:1472197616   DEBUG: ### [Legendas.TV] - Opening file: /home/osmc/.kodi/userdata/addon_data/service.subtitles.legendastv/temp/Extracted/Smurfs.The.Lost.Village.2017.BluRay.Subpack.PT-BR/Legenda Principal.srt
09:53:30.062 T:1472197616   DEBUG: ### [Legendas.TV] - Writing file: /home/osmc/.kodi/userdata/addon_data/service.subtitles.legendastv/temp/Extracted/Smurfs.The.Lost.Village.2017.BluRay.Subpack.PT-BR Legenda Principal.srt
09:53:30.065 T:1472197616   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 156: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/service.subtitles.legendastv/service.py", line 321, in <module>
                                                subs = Download(params["download_url"],'filename', pack, params['lang'])
                                              File "/home/osmc/.kodi/addons/service.subtitles.legendastv/service.py", line 170, in Download
                                                extract_and_copy()
                                              File "/home/osmc/.kodi/addons/service.subtitles.legendastv/service.py", line 137, in extract_and_copy
                                                log("Opening file: "+dirfile, "DEBUG")
                                              File "/home/osmc/.kodi/addons/service.subtitles.legendastv/resources/lib/LTVutilities.py", line 37, in log
                                                xbmc.log((u"### [%s] - %s" % (__scriptname__,msg,)).encode('utf-8'), level=loglevel )
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 156: ordinal not in range(128)
                                            -->End of Python script error report<--
09:53:30.073 T:1958962096   DEBUG: ------ Window Init (DialogNotification.xml) ------
```

image

**Comment by fernandog** [comment]
@MediaBrasil second commit fix the error:

Notice "Forçada" appears in the log.

```
10:41:35.631 T:1398768624   DEBUG: ### [Legendas.TV] - Opening URL: (http://legendas.tv/downloadarquivo/5957f03adb0b5)
10:41:38.552 T:1398768624   DEBUG: ### [Legendas.TV] - Opening file: /home/osmc/.kodi/userdata/addon_data/service.subtitles.legendastv/temp/Extracted/Movie.2017.BluRay.Subpack.PT-BR/Legenda Principal.srt
10:41:38.555 T:1398768624   DEBUG: ### [Legendas.TV] - Writing file: /home/osmc/.kodi/userdata/addon_data/service.subtitles.legendastv/temp/Extracted/Movie.2017.BluRay.Subpack.PT-BR Legenda Principal.srt
10:41:38.556 T:1398768624   DEBUG: ### [Legendas.TV] - Opening file: /home/osmc/.kodi/userdata/addon_data/service.subtitles.legendastv/temp/Extracted/Movie.2017.BluRay.Subpack.PT-BR/Legenda Forçada.srt
10:41:38.558 T:1398768624   DEBUG: ### [Legendas.TV] - Writing file: /home/osmc/.kodi/userdata/addon_data/service.subtitles.legendastv/temp/Extracted/Movie.2017.BluRay.Subpack.PT-BR Legenda Forcada.srt
10:41:38.559 T:1398768624   DEBUG: ### [Legendas.TV] - Opening file: /home/osmc/.kodi/userdata/addon_data/service.subtitles.legendastv/temp/Extracted/Legendas.tv.url
10:41:38.560 T:1398768624   DEBUG: ### [Legendas.TV] - Writing file: /home/osmc/.kodi/userdata/addon_data/service.subtitles.legendastv/temp/Extracted/Legendas.tv.url
```

**Comment by fernandog** [comment]
@gfjardim poderia verificar essa PR por favor?

**Pull request merged**
